apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: bogie
spec:
  components:
    - name: bogie-edge
      type: edge-worker
      properties:
        runtime:
          - bogie-mc
        image: ci4rail/bogie-edge:a6
        name: bogie-edge-container
        args: ["--config=/config/.bogie-edge-config.yaml"]
        #command: ["sh", "-c", "echo Hello && sleep 10000000"]
      traits:
        - type: edge-network-participant
          properties:
            networks:
              - bogie-network
        - type: volumes
          properties:
            volumes:
              - name: dbus
                type: hostPath
                path: /var/run/dbus
                mountPath: /var/run/dbus
                readOnly: false
              - name: avahi-daemon
                type: hostPath
                path: /var/run/avahi-daemon/socket
                mountPath: /var/run/avahi-daemon/socket
                readOnly: false
              - name: thermal
                type: hostPath
                path: /sys/class/thermal
                mountPath: /sys/class/thermal
                readOnly: false
              # Create with k create cm bogie-config --from-file=../../cmd/bogie-edge/.bogie-edge-config.yaml
              # Update with k create cm bogie-config --from-file=../../cmd/bogie-edge/.bogie-edge-config.yaml --dry-run -o yaml | kubectl replace -f -
              # Configuration is available in container under /config/.bogie-edge-config.yaml
              - name: bogie-config
                type: configMap
                cmName: bogie-config
                mountPath: /config
