#NatsAddress: "localhost:4222"
NetworkName: bogie-network
steadydrive:
  OutputDataRateHz: 1
  MotionSensor:
    DeviceAddress: S101-CPU01UC-accel
    SampleRate: 100
    FullScale: 4
    HighPassFilter: true
    BandwidthRatio: 2
gnss:
  GpsdURL: "172.17.0.1:2947"
position:
  MaxGnssAge: 20
triggerUnit:
  TriggerDuration: 0
  HoldOff: 5
  SteadyDrive:
    CompareType: 1
    Max: [0.01, 0.01, 0.01]
    RMS: [0.01, 0.01, 0.01]
  Position:
    MinLat: 0
    MaxLat: 100
    MinLon: 0
    MaxLon: 100
    MinSpeed: 0
    MaxSpeed: 200
sensor:
  BogieID: 1
  DeviceAddress:
    - S101-IOU01-USB-EXT-1-analogInTypeA1
    - S101-IOU01-USB-EXT-1-analogInTypeA2
    - S101-IOU01-USB-EXT-2-analogInTypeA1
    - S101-IOU01-USB-EXT-2-analogInTypeA2
  SampleRate: 4000
  RingBufEntries: 12000
metrics:
  PublishPeriod: 5
